### ISSUE TITLE
translate RUS 1.18 upd

### ISSUE THREAD

**Issue by Shelbikk** [jptrzy/infusion-table-mod#1]
[ru_ru.zip](https://github.com/jptrzy/infusion-table-mod/files/7669924/ru_ru.zip)

я перевёл именно так, потому что "Infuser table" есть в другом моде, трансфигурация - когда вы преобразуете одно в другое, примерно так я вижу ваш мод.

I translated it this way, because the 'Infuser table' is in another mod, transfiguration - when you transform one into another, this is how I see your mod.

**Comment by jptrzy** [comment]
Thank you for the contribution.
