### ISSUE TITLE
efficiency 6

### ISSUE THREAD

**Issue by RobGod389** [jptrzy/infusion-table-mod#3]
I traded for an enchanted tool with efficiency 6 through the mod called Goblin Traders by MrCrayFish and have converted the enchantment into a book through the infusion table. Now i cant put the book on a tool  and im stuck with a literally unusable book. could it be with minecraft that it only allows eff5?

**Comment by jptrzy** [comment]
What version of infusion-table-mod are you using?

**Comment by RobGod389** [comment]
v1.0.5, im playing on all of fabric 5 so i might suspect another mod restricting it or interfering but im not sure. i also just discovered that all efficiency books , even if combined for a higher efficiency do not work (the enchanted books that are from infusion table, not sure about the naturally spawned ones if there are any)
Edit: its a multiplayer server, on a single player it worked for me as i checked now

**Comment by jptrzy** [comment]
Thank you; I will look in it.

**Comment by yorii** [comment]
I believe the issue is not with the infusion table, but with some changes done to the anvil from another mod.

**Comment by unilock** [comment]
Anvils, at least in vanilla, when combining an item with a book containing an enchantment above its vanilla limit, will downgrade that book to its vanilla limit. For example, combining a pickaxe with a Fortune V book will result in a Fortune III pickaxe. I'm not sure if any mods in All of Fabric 5 changes this behavior. (try the Dragon Anvil?)

**Comment by jptrzy** [comment]
In my side everything works.
