### ISSUE TITLE
impossible to craft as you don't say what its made of

### ISSUE THREAD

**Issue by readwoodbox** [jptrzy/infusion-table-mod#6]
rack it up to total lack of documentation.   You show a pretty picture of what you are supposed to use to craft but an actual list of items in the description would be far more helpful.  I gather its two crystal shards.   Now what is the 4 pieces?  are they obsidian?  crying obsidian?  something else?   And the 3 stone pieces on the top?  OK   what sort of stone?  I've tried 10 different combinations without any luck.  so I am left wondering if its just a bug that you can't craft or I still don't have a clue what recipe is?

**Comment by Mahadbaloch** [comment]
Please download a recipe viewing mod like RIE as all mods will not have detailed recipes for every item.
Those are deepslate tiles btw
