### ISSUE TITLE
[Suggestion] Hoppers can insert the book and dispensers can use flint and steel

### ISSUE THREAD

**Issue by dathide** [jptrzy/infusion-table-mod#7]
Thanks for the great mod! I thought it would be cool to semi-automate the process of disenchanting using hoppers and dispensers. A hopper with books in it next to and facing the infusion table could insert a book if there isn't one already in place. Maybe if another hopper inserts an item that isn't a book, it attempts to place the item on top of the book. A dispenser next to and facing the infusion table could then use a flint and steel on it. Also, the infusion table could automatically insert the resulting enchanted book into any hopper beneath it.

**Comment by jptrzy** [comment]
I will think about this.
